///////////////////////////////////////////////////////////
//  IniciarSesion.cs
//  Implementation of the Class IniciarSesion
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:50 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace InicioSesion {
	public class IniciarSesion {
		private Context.FakeDbContext FakeContext;


		public IniciarSesion(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~IniciarSesion(){

		}

		/// 
		/// <param name="User"></param>
		public bool Response(Usuario User){
			return FakeContext.UsersList.FindAll(x => 
				x.NombreUsuario == User.NombreUsuario 
				&& x.Contrasena == User.Contrasena
			).Count > 0;
		}

		/// 
		/// <param name="UserRequest"></param>
		public void Validate(Usuario UserRequest){
			if (UserRequest.Equals(null)){
				throw new NullReferenceException();
			}
		}

	}//end IniciarSesion

}//end namespace InicioSesion