///////////////////////////////////////////////////////////
//  RegistrarLog.cs
//  Implementation of the Class RegistrarLog
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:51 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace InicioSesion {
	public class RegistrarLog {
		private Context.FakeDbContext FakeContext;


		public RegistrarLog(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~RegistrarLog(){

		}

		/// 
		/// <param name="User"></param>
		public bool Response(Usuario User){

			FakeContext.LogsList.Add(new Log{
				Id = FakeContext.LogsList.Count + 1,
				User = User
			});
			return true;
		}

		/// 
		/// <param name="User"></param>
		public void Validate(Usuario User){
			if (User.Equals(null)){
				throw new NullReferenceException();
			}
		}

	}//end RegistrarLog

}//end namespace InicioSesion