///////////////////////////////////////////////////////////
//  ValidarInformacionUsuario.cs
//  Implementation of the Class ValidarInformacionUsuario
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:54 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace ConsultaUsuarios {
	public class ValidarInformacionUsuario {
		private Context.FakeDbContext FakeContext;


		public ValidarInformacionUsuario(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~ValidarInformacionUsuario(){

		}

		/// 
		/// <param name="Usuario"></param>
		public Entities.Usuario Response(Usuario Usuario){

			return FakeContext.UsersList.Find(x => 
						x.Correo == Usuario.Correo
						|| x.Nombre == Usuario.Nombre
						|| x.Celular == Usuario.Celular
					);
		}

		/// 
		/// <param name="User"></param>
		public void Validate(Usuario User){
			if (User.Equals(null)){
				throw new NullReferenceException();
			}
		}

	}//end ValidarInformacionUsuario

}//end namespace ConsultaUsuarios