///////////////////////////////////////////////////////////
//  ValidarLogsRecientesUsuario.cs
//  Implementation of the Class ValidarLogsRecientesUsuario
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:54 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace ConsultaUsuarios {
	public class ValidarLogsRecientesUsuario {
		private Context.FakeDbContext FakeContext;


		public ValidarLogsRecientesUsuario(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~ValidarLogsRecientesUsuario(){

		}

		/// 
		/// <param name="User"></param>
		public List<Log> Response(Usuario User){

			return FakeContext.LogsList.FindAll(x => x.User.Id == User.Id);
		}

		/// 
		/// <param name="User"></param>
		public void Validate(Usuario User){
			if (User.Equals(null)){
				throw new NullReferenceException();
			}
		}

	}//end ValidarLogsRecientesUsuario

}//end namespace ConsultaUsuarios