///////////////////////////////////////////////////////////
//  ValidarExistenciaUsuario.cs
//  Implementation of the Class ValidarExistenciaUsuario
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:54 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace ConsultaUsuarios {
	public class ValidarExistenciaUsuario {
		private Context.FakeDbContext FakeContext;


		public ValidarExistenciaUsuario(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~ValidarExistenciaUsuario(){

		}

		/// 
		/// <param name="Usuario"></param>
		public List<Usuario> Response(){
			return FakeContext.UsersList;
		}

		/// 
		public void Validate(){
			if (FakeContext.UsersList.Count == 0){
				throw new NullReferenceException();
			}
		}

	}//end ValidarExistenciaUsuario

}//end namespace ConsultaUsuarios