///////////////////////////////////////////////////////////
//  Log.cs
//  Implementation of the Class Log
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 1:15:20 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace Entities {
	public class Log {

		public DateTime Fecha {get; set;}
		public int Id {get; set;}
		public Usuario User {get; set;}

		public Log(){

		}

		~Log(){

		}

	}//end Log

}//end namespace Entities