///////////////////////////////////////////////////////////
//  Roles.cs
//  Implementation of the Class Roles
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 1:15:20 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace Entities {
	public class Roles {

		public int Id {get; set;}
		public string Nombre {get; set;}

		public Roles(){

		}

		~Roles(){

		}

	}//end Roles

}//end namespace Entities