///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 1:15:20 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace Entities {
	public class Usuario {

		public int Celular {get; set;}
		public string Contrasena {get; set;}
		public string Correo {get; set;}
		public int Id {get; set;}
		public string Nombre {get; set;}
		public string NombreUsuario {get; set;}
		public Roles Rol {get; set;}

		public Usuario(){

		}

		~Usuario(){

		}

	}//end Usuario

}//end namespace Entities