///////////////////////////////////////////////////////////
//  AsignarRol.cs
//  Implementation of the Class AsignarRol
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:42 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace RegistroInicio {
	public class AsignarRol {
		private Context.FakeDbContext FakeContext;


		public AsignarRol(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~AsignarRol(){

		}

		/// 
		/// <param name="NuevoUsuario"></param>
		public bool Response(Usuario NuevoUsuario){
			var User = FakeContext.UsersList.Find(x => x.Id == NuevoUsuario.Id);
			
			return true;
		}

		/// 
		/// <param name="Usuario"></param>
		public void Validate(Usuario Usuario){
			if (Usuario.Equals(null)){
				throw new NullReferenceException();
			}
		}

	}//end AsignarRol

}//end namespace RegistroInicio