///////////////////////////////////////////////////////////
//  RegistrarUsuarios.cs
//  Implementation of the Class RegistrarUsuarios
//  Generated by Enterprise Architect
//  Created on:      05-sept.-2021 7:18:42 p. m.
//  Original author: Daniel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entities;
namespace RegistroInicio {
	public class RegistrarUsuarios {
		private Context.FakeDbContext FakeContext;


		public RegistrarUsuarios(Context.FakeDbContext _FakeContext){
			FakeContext = _FakeContext;
		}

		~RegistrarUsuarios(){

		}

		/// 
		/// <param name="NuevoUsuario"></param>
		public bool Response(Usuario NuevoUsuario){
			NuevoUsuario.Id = FakeContext.UsersList.Count + 1;
			FakeContext.UsersList.Add(NuevoUsuario);			
			return FakeContext.UsersList.Contains(NuevoUsuario);
		}

		/// 
		/// <param name="User"></param>
		public void Validate(Usuario User){
			if (User.Equals(null)){
				throw new NullReferenceException();
			}

			if(FakeContext.UsersList.FindAll(x => x.NombreUsuario == User.NombreUsuario).Count > 0){
				throw new InvalidOperationException();
			}
		}

	}//end RegistrarUsuarios

}//end namespace RegistroInicio